In [1]:
from IPython.display import Image

from colorbrains_research import get_apidata
from colorbrains_research.display_plots.mpl_plots import basecolors, cmy_comparisons

### Matplotlib Categorized Colormaps
Matplotlib has pregenerated colormaps https://matplotlib.org/stable/tutorials/colors/colormaps.html <br>
With the exception of `Qualitative`, color sets designed to be as differentiating as possible, these sets are all intended for continous variables.<br>


Each colormap has a predefined number of steps where data at the 0 or n ends of the curve have the most extreme colors within the set.<br>
Qualitative data is designed for data with an aribitrary binning of data. Useful for categorical data. Designed to be as differentiating as possible.<br>

`Cyclic` colormaps are used where there is some periodicity in the data (`sin`, `cosine`, etc)

`Diverging` has three colors representing a divergence and direction from a specified midpoint. Colors gradient from a middle color towards a pole with a unique color.
- temperature data
- rainfall
- velocity

In [2]:
print(get_apidata.get_categorized_colormaps().shape)
cat_cmapdf = get_apidata.get_categorized_colormaps()
display(cat_cmapdf)
cat_cmapdf.groupby(['categorical_name'])['cmap_n_total'].describe()
print(get_apidata.get_colormaps().shape)
get_apidata.get_colormaps().head()

(83, 3)

                 categorical_name  colormap_name  cmap_n_total
0   PerceptuallyUniformSequential        viridis           256
1   PerceptuallyUniformSequential         plasma           256
2   PerceptuallyUniformSequential        inferno           256
3   PerceptuallyUniformSequential          magma           256
4   PerceptuallyUniformSequential        cividis           256
..                            ...            ...           ...
78                  Miscellaneous        rainbow           256
79                  Miscellaneous            jet           256
80                  Miscellaneous          turbo           256
81                  Miscellaneous  nipy_spectral           256
82                  Miscellaneous      gist_ncar           256

[83 rows x 3 columns]

(18828, 5)

  colormap_name  cmap_n_observation       red     green      blue
0       viridis                   1  0.267004  0.004874  0.329415
1       viridis                   2  0.268510  0.009605  0.335427
2       viridis                   3  0.269944  0.014625  0.341379
3       viridis                   4  0.271305  0.019942  0.347269
4       viridis                   5  0.272594  0.025563  0.353093